components:
  schemas:
    InternalServerError:
      description: Internal Server Error
      properties:
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - msg
      - type
      title: InternalServerError
      type: object
    InvalidArgument:
      description: Bad Request
      properties:
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - msg
      - type
      title: InvalidArgument
      type: object
    NotFound:
      description: Not Found
      properties:
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - msg
      - type
      title: NotFound
      type: object
info:
  contact:
    email: contact@bentoml.com
    name: BentoML Team
  description: "# stt:None\n\n[![pypi_status](https://img.shields.io/badge/BentoML-1.1.10-informational)](https://pypi.org/project/BentoML)\n
  title: stt
  version: None
openapi: 3.0.2
paths:
  /livez:
    get:
      description: Health check endpoint for Kubernetes. Healthy endpoint responses
        with a <code>200</code> OK status.
      responses:
        '200':
          description: Successful Response
      tags:
      - Infrastructure
  /metrics:
    get:
      description: Prometheus metrics endpoint. The <code>/metrics</code> responses
        with a <code>200</code>. The output can then be used by a Prometheus sidecar
        to scrape the metrics of the service.
      responses:
        '200':
          description: Successful Response
      tags:
      - Infrastructure
  /process_audio:
    post:
      consumes:
      - null
      description: ''
      operationId: stt__process_audio
      produces:
      - application/json
      requestBody:
        content:
          '*/*':
            schema:
              format: binary
              type: string
        required: true
        x-bentoml-io-descriptor:
          args:
            kind: binaryio
            mime_type: null
          id: bentoml.io.File
      responses:
        200:
          content:
            application/json:
              schema:
                type: object
          description: Successful Response
          x-bentoml-io-descriptor:
            args:
              has_json_encoder: false
              has_pydantic_model: false
            id: bentoml.io.JSON
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidArgument'
          description: Bad Request
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
          description: Not Found
        500:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
          description: Internal Server Error
      summary: "InferenceAPI(BytesIOFile \u2192 JSON)"
      tags:
      - Service APIs
      x-bentoml-name: process_audio
  /readyz:
    get:
      description: A <code>200</code> OK status from <code>/readyz</code> endpoint
        indicated the service is ready to accept traffic. From that point and onward,
        Kubernetes will use <code>/livez</code> endpoint to perform periodic health
        checks.
      responses:
        '200':
          description: Successful Response
      tags:
      - Infrastructure
servers:
- url: .
tags:
- description: BentoML Service API endpoints for inference.
  name: Service APIs
- description: Common infrastructure endpoints for observability.
  name: Infrastructure
